apiVersion: v1
kind: Secret
metadata:
  name: savepoint-secrets
  namespace: savepoint
type: Opaque
stringData:
  MSSQL_SA_PASSWORD: YourStrong!Passw0rd
  ConnectionStrings__DefaultConnection: Server=savepoint-db,1433;Database=SavePoint;User Id=sa;Password=YourStrong!Passw0rd;TrustServerCertificate=True;Encrypt=False
